// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZ2XpbWKKU3-vGdusxgTBQSTx_IqYhCY',
    appId: '1:738811647176:web:afbf0ea7b8306653ed01fd',
    messagingSenderId: '738811647176',
    projectId: 'flutterfire-apple-dev',
    authDomain: 'flutterfire-apple-dev.firebaseapp.com',
    storageBucket: 'flutterfire-apple-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJcjAdGVO9ygw7W8anweydtx5Lt7ioXVk',
    appId: '1:738811647176:android:830ce6ba787d3a91ed01fd',
    messagingSenderId: '738811647176',
    projectId: 'flutterfire-apple-dev',
    storageBucket: 'flutterfire-apple-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvMax8p-_3lw1W0fRD5dI8UcdtYbsD0mk',
    appId: '1:738811647176:ios:9427709d95cf886aed01fd',
    messagingSenderId: '738811647176',
    projectId: 'flutterfire-apple-dev',
    storageBucket: 'flutterfire-apple-dev.appspot.com',
    iosClientId: '738811647176-rjq40ro6olqdknvpbjv28q1brig0a39n.apps.googleusercontent.com',
    iosBundleId: 'jp.susatthi.flutterfireSample.dev',
  );
}
